### ISSUE TITLE
Raw LZMA Stream

### ISSUE THREAD

**Issue by mjachym99** [jcmellado/dart-lzma#11]
I’m building a QR Code generator based on the Slovak PayBySquare standard. They use the LZMA algorithm in one of the steps of data encoding, and I need a raw LZMA stream.

What I want to achieve is equivalent to the result of python code in [this repository](https://github.com/matusf/pay-by-square/blob/master/pay_by_square.py#L61) (this is an implementation of the PayBySquare standard in Python) or [this code](https://github.com/xseman/bysquare/blob/develop/src/main.ts#L69) written in TypeScript.

I tested the default python implementation of lzma and compared it to the implementation in Dart (I changed dictionary size to 2^17).

Here are the results:
Python – [Google Colab Notebook](https://colab.research.google.com/drive/1Y9UURWXri5WraBM4v08MoIhYoV-E5tVJ?usp=sharing)

Raw data: [84, 101, 115, 116, 9, 84, 101, 115, 116]
Compressed data: [0, 42, 25, 74, 103, 107, 200, 221, 124, 194, 127, 255, 255, 237, 120, 0, 0]
Size of compressed data in bytes: 17
Original data after decompression: [84, 101, 115, 116, 9, 84, 101, 115, 116]

Dart (using lzma package with changed dictionary size 2^17):

I/flutter (25728): Raw data: [84, 101, 115, 116, 9, 84, 101, 115, 116]
I/flutter (25728): Compressed data: [93, 0, 0, 2, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 42, 25, 74, 103, 107, 200, 221, 87, 160, 0, 0]
I/flutter (25728): Compressed data size: 25
I/flutter (25728): Original data after decompression: [84, 101, 115, 116, 9, 84, 101, 115, 116]

Data output from Dart implementation seems to have the 13-byte .lzma header, some bytes are then the same (starting from […, 0, 42, 25, 74, …] but then there are discrepancies at later indexes.

Is it possible to achieve with this package?

**Comment by jcmellado** [comment]
The first 5 bytes are the [parameters](https://github.com/jcmellado/dart-lzma/blob/master/lib/src/encoder.dart#L31) used for the codec (see [writeCoderProperties](https://github.com/jcmellado/dart-lzma/blob/master/lib/src/encoder.dart#L1309)):
```
93, 0, 0, 2, 0
```

The next 8 bytes are the original [length](https://github.com/jcmellado/dart-lzma/blob/master/lib/src/encoder.dart#L62) of the input:
```
9, 0, 0, 0, 0, 0, 0, 0
```

The compressed data depends of the implementation and used parameters.

**Comment by mjachym99** [comment]
Okay, so what I did was change [eos parameter](https://github.com/jcmellado/dart-lzma/blob/master/lib/src/encoder.dart#L38) to true to add End-Of-Stream marker to the compressed data ( see [STREAMED vs. NON-STREAMED](http://www.manpagez.com/man/1/lzma/lzma-4.32.7.php) section).

After the change, the results are as I needed. 
It would be beneficial to add some API to make it possible to change parameters in runtime.
