### ISSUE TITLE
lzma / lzma 2

### ISSUE THREAD

**Issue by DanielSoCra** [jcmellado/dart-lzma#4]
This library currently implements lzma 2, right?

Is there any possibilty anyone could give me a hint on the difference beteween the two and the effort needed to implement the "original" lzma, too?

**Comment by jcmellado** [comment]
As state in the main page of the project, this library is a port of LZMA compression algorithm to Dart taken from the original Java version found on the [LZMA SDK](https://www.7-zip.org/sdk.html).

AFAIK Java source code implements LZMA:

> Java source code for LZMA compression and decompression

**Comment by isoos** [comment]
My understanding is that lzma 2 is more about creating wrapper blocks which (a) can be compressed in parallel and (b) can store data without compression (e.g. because it was already compressed). Inside the blocks it is still lzma.
