### ISSUE TITLE
Support nullsafety

### ISSUE THREAD

**Issue by NicolaVerbeeck** [jcmellado/dart-lzma#5]
Please update the library to dart sdk 2.12 with nullsafety support

**Comment by isoos** [comment]
@NicolaChimerapps: I am not actively using the library, but if you do the migration and create a pull request for it, I'm happy to review and publish.

**Comment by NicolaVerbeeck** [comment]
There we go

**Comment by NicolaVerbeeck** [comment]
Fixed in #6

**Comment by isoos** [comment]
Apparently there is still an analyzer issue in the code:
https://pub.dev/packages/lzma/score

@NicolaChimerapps could you please take a look on what's happening there?

**Comment by NicolaVerbeeck** [comment]
It would seem that whoever pushed the library to pub.dev has some non-checked-in files (lib/bench.dart) locally on his device. This should never happen.

**Comment by isoos** [comment]
> It would seem that whoever pushed the library to pub.dev has some non-checked-in files (lib/bench.dart) locally on his device. This should never happen.

Opps, that's on me.

**Comment by isoos** [comment]
Fixed, and deployed a new version.
