### ISSUE TITLE
Can't decode SQZ file

### ISSUE THREAD

**Issue by jitendrapurohit12** [jcmellado/dart-lzma#9]
I tried to decode a .SQZ file using this package, but it cant decode them. I tried with multiple files.
Steps:
1. Creating a file in a temporary file from app Assets
2. providing lzma.decode() the byte array from the generated file from the previous step.

here is the code:

`  Future<void> decode() async {
    final byteData = await rootBundle.rootBundle.load('assets/tes2.docx.SQZ');
    final file = File('${(await getTemporaryDirectory()).path}/tes2.docx.SQZ');
    await file
        .writeAsBytes(byteData.buffer.asUint8List(byteData.offsetInBytes, byteData.lengthInBytes));
    final decoded = lzma.decode(file.readAsBytesSync());
    print(decoded);
  }`

here is the error:

E/flutter ( 9277): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Exception: Error in data stream
E/flutter ( 9277): #0      decompress
package:lzma/src/decoder.dart:55
E/flutter ( 9277): #1      LzmaDecoder.convert
package:lzma/lzma.dart:41
E/flutter ( 9277): #2      Codec.decode (dart:convert/codec.dart:26:34)
E/flutter ( 9277): #3      _ScreenSQZTestState.decode
package:fcm/screen_sqz_test.dart:24
E/flutter ( 9277): <asynchronous suspension>

 Can someone help?

**Comment by jcmellado** [comment]
Probably the content of the file is not encoded using LZMA.

**Comment by jitendrapurohit12** [comment]
File was not correctly encrypted.
